from pydantic import BaseModel, Field
from typing import Any, Literal, Union,Annotated,List


class RouteQuery(BaseModel):
    """ 
        This function is find tool of user query to the most relvant datasource.
        model is possible one of choice about 'normal_generate', 'web_search','vectorstore'
    """
    datasource : Literal['normal_generate','web_search','vectorstore']= Field(
        ...,
        description = 'Given a user "query" or "question", you choose to route web_search or a vectorstore or normal generate'
    )

class GradeDocument(BaseModel):
    """ 
        수집된 문서에서 마다 relevant 를 측정하여 관련성 높은 문서만 수집하는 기법
    
    """
    datasource : Literal['yes', 'no'] = Field(
        ...,
        description = 'Determine whether the given document and question are relevant, and answer with "yes" or "no".'
    )


class GradeHallucinations(BaseModel):
    """ 
        retriver 된 데이터와 answer 간의 연관성 확인 
        할루시네이션 : 모델이 상상력을통해 생성한 답변
    
    """
    datasource : Literal['yes', 'no'] = Field(
        ...,
        description = 'Answer "yes" or "no" based on whether the answer generated by the LLM is factually consistent with the retrieval.'
    )

class GradeAnswer(BaseModel):
    """ 
        고객의 질문과 최동 답변간의 연관성 확
    
    """
    datasource : Literal['yes', 'no'] = Field(
        description = 'Indicate "yes" or "no" whether the answer solves the question'
    )


class MusicPlan(BaseModel):
    """Sorted steps to execute the plan"""
    steps: Annotated[List[str],"Different steps to follow, should be in sorted order"]

class MusicResponse(BaseModel):
    """Response to user."""
    # 사용자 응답
    response: str

class MusicAct(BaseModel):
    """Action to perform."""
    # LLM 이 판단하여 Reponse 인지 Plan 인지 선택하는 모델
    # 만약 Response 인경우 response 변수에 답변 생성
    # 그외 Plan 인경우 step 변수에 답변 생성
    action: Union[MusicResponse, MusicPlan] = Field(
        description="Action to perform. " \
        "If you want to respond to user, use Response. "
        "If you need to further use tools to get the answer, use Plan."
    )


class RouteModel(BaseModel):
    """ 
        retriver 된 데이터와 answer 간의 연관성 확인 
        할루시네이션 : 모델이 상상력을통해 생성한 답변
    
    """
    datasource : Literal['web_search_agent', 'pdf_loader_agent','db_agent','conversation_agent'] = Field(
        ...,
        description = '' \
        '`web_search_agent` is web search possible. '
        '`pdf_loader_agent` is use vectorstore.' \
        '`db_agent` is use database.' \
        '`conversation_agent` is everyday interactive talk agents '

    )