from pydantic import BaseModel, Field
from typing import Any, Literal, Union, Annotated, List


class RouteQuery(BaseModel):
    """
    This function is find tool of user query to the most relvant datasource.
    model is possible one of choice about 'normal_generate', 'web_search','vectorstore'
    """

    datasource: Literal["normal_generate", "web_search", "vectorstore"] = Field(
        ...,
        description='Given a user "query" or "question", you choose to route web_search or a vectorstore or normal generate',
    )


class GradeDocument(BaseModel):
    """
    수집된 문서에서 마다 relevant 를 측정하여 관련성 높은 문서만 수집하는 기법

    """

    datasource: Literal["yes", "no"] = Field(
        ...,
        description='Determine whether the given document and question are relevant, and answer with "yes" or "no".',
    )


class GradeHallucinations(BaseModel):
    """
    retriver 된 데이터와 answer 간의 연관성 확인
    할루시네이션 : 모델이 상상력을통해 생성한 답변

    """

    datasource: Literal["yes", "no"] = Field(
        ...,
        description='Answer "yes" or "no" based on whether the answer generated by the LLM is factually consistent with the retrieval.',
    )


class GradeAnswer(BaseModel):
    """
    고객의 질문과 최동 답변간의 연관성 확

    """

    datasource: Literal["yes", "no"] = Field(
        description='Indicate "yes" or "no" whether the answer solves the question'
    )


class PlanListModel(BaseModel):
    """Sorted steps to execute the plan"""

    steps: Annotated[List[str], "Different steps to follow, should be in sorted order"]


class MusicResponse(BaseModel):
    """Response to user."""

    # 사용자 응답
    response: str


class MusicAct(BaseModel):
    """Action to perform."""

    # LLM 이 판단하여 Reponse 인지 Plan 인지 선택하는 모델
    # 만약 Response 인경우 response 변수에 답변 생성
    # 그외 Plan 인경우 step 변수에 답변 생성
    action: Union[MusicResponse, PlanListModel] = Field(
        description="Action to perform. "
        "If you want to respond to user, use Response. "
        "If you need to further use tools to get the answer, use Plan."
    )


class RouteModel(BaseModel):
    """
    retriver 된 데이터와 answer 간의 연관성 확인
    할루시네이션 : 모델이 상상력을통해 생성한 답변

    """

    datasource: Literal[
        "web_search_agent", "db_agent", "data_analysis", "conversation_agent"
    ] = Field(
        ...,
        description=""
        "`web_search_agent` is web search possible. "
        "`db_agent` is use database."
        "`data_analysis` is use python code."
        "`conversation_agent` is normal conversation.",
    )

    # datasource: Literal[
    #     "web_search_agent", "pdf_loader_agent", "db_agent", "conversation_agent"
    # ] = Field(
    #     ...,
    #     description=""
    #     "`web_search_agent` is web search possible. "
    #     "`pdf_loader_agent` is use vectorstore."
    #     "`db_agent` is use database."
    #     "`conversation_agent` is everyday interactive talk agents ",
    # )


# class FeedbackModel(BaseModel):
#     """
#     사용자의 Question 의 내용을 분석하여 사용자의 순수한 질의, 요청일 경우 False 처리
#     AI 가 어떠한 판단한 내용의 대한 사람의 피드백, 또는 응답일경우네느 True 로 처리

#     """

#     datasource: Literal["yes", "no"] = Field(
#         description="""
#             If there is one history, return 'no'
#             If you have 2 or more history, analyze the last 2 messages and the AI asks a question and the human responds 'yes' and otherwise 'no'
#             """
#     )


class FeedbackModel(BaseModel):
    """ """

    datasource: Literal[
        "request_node",
        "response_node",
    ] = Field(
        ...,
        description=""" 
        Here are two parameters
        The question parameter includes a user's question or answer

        In the case of answer, include the answer

        Understand the meaning of question and answer, answer request_node if the user requests, and answer response_node if the user is responding to an AI request
        """,
    )


class GradeQuery(BaseModel):
    """
    고객의 질문과 최동 답변간의 연관성 확

    """

    datasource: Literal["yes", "no"] = Field(
        description='Indicate "yes" or "no" whether the answer solves the question'
    )
