import os, sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname("utils"), "..")))
from module.utils import *
from module.prompt import *
from module.custom_model import *
from module.tools import *
from module.db_agent import *
from module.data_analysis_agent import *
from module.conversaction_agent import *

from typing_extensions import TypedDict

from typing import Annotated, List, Literal, Tuple
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import (
    AIMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
    RemoveMessage,
)
from langgraph.prebuilt import create_react_agent
from langchain_core.tools import tool
from langchain_core.runnables import RunnableLambda, RunnableWithFallbacks
from langgraph_supervisor import create_supervisor


class State(TypedDict):
    question: Annotated["str", "human request to llm"]
    summary: Annotated[str, "previous messages summarization "]
    messages: Annotated[list, add_messages]  # 화면 출력용
    answer: Annotated["str", "llm generate answer"]


def get_prompt_summary():
    template = """ 
        #System :
        As a summary-only node in LangGraph, you are responsible for summarizing key information by receiving records from previous conversations.  
        Be sure to follow the following rules:

        # Rules:
        1. If the user's requirements are **Analyzing, Comparison, Evaluation, and Modification requests for answers generated by previous LLM:
        - Never summarize the answers generated by the previous LLM and keep the original ****.
        - Combine content by briefly summarizing other surrounding contexts (e.g., discussion process, question background, etc.)

        2. For common conversations (information queries, descriptions, requests, etc.) that do not meet the above conditions:
        - Only important contents are summarized in **sentence form.**.
        - Remove unnecessary detailed descriptions, duplicate sentences, and text repeated in context.
        - It is described focusing on facts, and opinions or expressions of emotions are excluded.

        3. Finally, the summary is written in Korean.

        # Enter :
        - User Request : {question}
        - LLM's previous answer : {answer}
        - All previous conversations : {messages}
        - Summary of the conversation : {summary}
    """
    return ChatPromptTemplate.from_template(template)


def summary_node(state: State):
    """
    이전 모든 대화 내용중 핵심을 포함하여 요약하기위한 노드
    messages 가 6개 이상인 경우 summarization 수행
    """
    question = state.get("question", "")
    messages = state.get("messages", "")
    answer = state.get("answer", "")
    summary = state.get("summary", "")
    chain = get_prompt_summary() | get_gemini()
    response = chain.invoke(
        {
            "question": question,
            "messages": messages,
            "answer": answer,
            "summary": summary,
        }
    )
    if len(messages) > 2:
        # 오래된 메시지 삭제
        delete_messages = [RemoveMessage(id=m.id) for m in state["messages"]]
        # 요약 정보 반환
        return {
            "summary": response.content,
            "messages": delete_messages,
        }
    else:
        return {
            "summary": response.content,
        }


def supervisor_node(state: State):
    """
    두개의 에이전트를 자율적으로 선택하여 사용하는 관리자에이전트 구조
    """
    summary = state.get("summary", "")
    question = state["question"]
    content = f"Previous Conversations: {summary} \n Human Request : {question}"
    db = get_db_agent()
    conversation = get_conversation_agent()
    data_analysis = get_data_analysis_agent()
    supervisor = create_supervisor(
        model=get_gpt(),
        agents=[db, conversation, data_analysis],
        prompt=(
            "You are a supervisor managing three agents:\n"
            "- db_agent: assign database select,insert,delete,update tasks\n"
            "- conversation_agent: assign normal conversaction and no use agent\n"
            "- data_analysis_agent: Agents that generate and run Python code for data analysis\n"
            "# Important : you must final answer is Korean\n"
        ),
        add_handoff_back_messages=True,
        output_mode="full_history",
    ).compile()
    inputs = {"messages": [{"role": "user", "content": content}]}
    config = get_runnable_config(recursion_limit=15, thread_id=get_random_uuid())
    for step, metadata in supervisor.stream(inputs, config, stream_mode="messages"):
        # final_step = step
        # fianl_metadata = metadata
        return {"step": step, "metadata": metadata}
    # return final_step, fianl_metadata
    # result = supervisor.invoke(inputs, {"recursion_limit": 15})
    # messages = result["messages"]
    # return {"messages": messages, "history": messages, "answer": messages[-1].content}


def get_graph():
    state_graph = StateGraph(State)
    state_graph.add_node("summary_node", summary_node)
    state_graph.add_node("supervisor_node", supervisor_node)

    state_graph.add_edge(START, "summary_node")
    state_graph.add_edge("summary_node", "supervisor_node")
    state_graph.add_edge("supervisor_node", END)

    cp = get_check_pointer()
    return state_graph.compile(checkpointer=cp)


def get_config():
    return get_runnable_config(recursion_limit=10, thread_id=get_random_uuid())
